let
    Source = Table.NestedJoin(
        #"Employees Staging", {"ParentEmployeeKey"}, Managers, {"EmployeeKey"}, "Managers", JoinKind.LeftOuter
        )
in
    Source
